# Generated by Django 4.2 on 2023-04-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=25)),
                ('jins', models.CharField(max_length=25)),
                ('shahar', models.CharField(blank=True, max_length=25)),
                ('tugulgan_yil', models.PositiveSmallIntegerField()),
                ('rasm', models.FileField(blank=True, null=TimeoutError, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
