# Generated by Django 4.2 on 2023-04-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brend', models.CharField(max_length=30)),
                ('holat', models.CharField(default='yang', max_length=30)),
                ('batavsil', models.TextField(blank=True)),
                ('narx', models.PositiveSmallIntegerField()),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
                ('rasm', models.FileField(blank=True, null=True, upload_to='mahsulot')),
                ('mavjud', models.BooleanField(default=True)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosy_app.bolim')),
                ('sotuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
    ]
