# Generated by Django 4.1.6 on 2023-04-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('assosy_app', '0002_izoh'),
        ('buyurtma_app', '0002_remove_savat_mahsulot_remove_savat_profil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavatItm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField(default=1)),
                ('sana', models.PositiveSmallIntegerField(default=True)),
                ('ummumiy_summa', models.IntegerField(blank=True, null=True)),
                ('yetkazish_puli', models.PositiveSmallIntegerField(default=15000)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosy_app.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosy_app.mahsulot')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(max_length=25)),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.IntegerField(blank=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
            ],
        ),
    ]
