# Generated by Django 4.1.6 on 2023-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma_app', '0003_savatitm_savat_buyurtma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savat',
            name='mahsulot',
        ),
        migrations.AddField(
            model_name='savat',
            name='sana',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
