# Generated by Django 4.1.6 on 2023-04-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma_app', '0004_remove_savat_mahsulot_savat_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savatitm',
            name='mahsulot',
        ),
        migrations.DeleteModel(
            name='Buyurtma',
        ),
        migrations.DeleteModel(
            name='SavatItm',
        ),
    ]
