# Generated by Django 4.1.6 on 2023-04-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma_app', '0009_alter_buyurtma_summa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyurtma',
        ),
    ]
