# Generated by Django 4.1.6 on 2023-04-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('buyurtma_app', '0010_delete_buyurtma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(max_length=25)),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.PositiveSmallIntegerField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.profil')),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma_app.savat')),
            ],
        ),
    ]
