# Generated by Django 4.1.6 on 2023-04-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma_app', '0011_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtma',
            name='summa',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
